### ISSUE TITLE
Erro de versões da biblioteca html-webpack-plugin

### ISSUE THREAD

**Issue by danfilg** [rubemfsv/clean-react-app#1]
Tentei usar o projeto como boilerplate, porém dá conflito entre as versões do html-webpack-plugin. Vou tentar abrir um PR consertando, porém, se puder olhar isso também. Pode acontecer com outros que forem usar o projeto.

![image](https://user-images.githubusercontent.com/49797722/185722789-4353798d-6ae1-4750-9c78-a5591b71c2fd.png)

**Comment by rubemfsv** [comment]
Resolvido!
