### ISSUE TITLE
Implement Unit Tests for FormLoaderStatus Component

### ISSUE THREAD

**Issue by rubemfsv** [rubemfsv/clean-react-app#10]
This issue is focused on implementing unit tests for the FormLoaderStatus component within our project. Unit testing is a crucial aspect of software development that helps ensure the reliability and correctness of individual code units, such as components.

**Goals:**

- Create comprehensive unit tests for the FormLoaderStatus component to validate its functionality.
- Verify that the FormLoaderStatus component behaves as expected.
- Ensure that any changes or updates to the FormLoaderStatus component in the future do not introduce regressions.

**Tasks:**

1. Write unit tests that cover different aspects of the FormLoaderStatus component (e.g., rendering spinner when loading, show error messages).
2. Validate the accessibility of the FormLoaderStatus component, ensuring it meets accessibility standards.
3. Ensure that the tests provide sufficient code coverage for the Button component.

**Guidelines:**

- Follow best practices for unit testing.
- Write clear and descriptive test cases that cover both typical and edge cases.
- Pay attention to code quality, readability, and maintainability when writing tests.

**Comment by vibh1103** [comment]
Hi can you assign this task to me i can work on it ?

**Comment by rubemfsv** [comment]
Hey, @vibh1103, of course! Don't forget to ensure commit messages are following the conventional commits :smile:

**Comment by vibh1103** [comment]
Hi @rubemfsv  Please review the PR

**Comment by rubemfsv** [comment]
Hey, @vibh1103, I did a review and put some comments!

**Comment by vibh1103** [comment]
let me fix those thanks

**Comment by vibh1103** [comment]
@rubemfsv  I made some changes in PR can you please review again.

**Comment by vibh1103** [comment]
Thanks @rubemfsv. 
Please tell me if any other issue i can pick ?

**Comment by rubemfsv** [comment]
@vibh1103 I have other open issues here. And I also have this other project needing LICENSE file and other improvements: https://github.com/rubemfsv/Github-Explorer-Mobile-Clean-Architecture
Just open an issue!

Thanks
