### ISSUE TITLE
Enhance README with Collaborators Section

### ISSUE THREAD

**Issue by rubemfsv** [rubemfsv/clean-react-app#12]
The README file serves as a crucial source of information for our project. To foster transparency and acknowledge the valuable contributions from our team members and collaborators, we should add a dedicated "Collaborators" section to the README. This small but meaningful addition reflects our commitment to open collaboration and transparency.

**Goals:**

- In the end of the README, create a new section within the README that showcases our project's collaborators.
- Recognize and give credit to the individuals who have contributed to the project's success.
- Provide acknowledgment information for collaborators (e.g., https://github.com/all-contributors/all-contributors, https://github.com/testing-library/testing-library-docs).
- Foster a sense of community and collaboration among the project.

**Tasks:**

1. Edit the README file to include a new section titled "Collaborators" (you can adjust the "Branches and contributions" section)
2. Compile a list of project collaborators, including their names and informations.
3. Ensure that the new section is formatted consistently with the rest of the README, maintaining readability and clarity.
4. Verify that all information presented in the "Collaborators" section is up to date and accurate.
5. Consider including any additional details or content that would enrich the collaborator profiles.

Guidelines:

- Be respectful and accurate in the descriptions and acknowledgments of collaborators.
- Keep the "Collaborators" section organized and easy to read.

**Comment by Vijaykv5** [comment]
Would love to work on it. May you can assign. me the issue?

**Comment by Vijaykv5** [comment]
Is this format fine? @rubemfsv (Here the User images will be replaced by contributors profile pictures)

Does any other things to be included?

Also you know how it can be automatically made into contributors list if One has contributed to some issues

<img width="803" alt="Screenshot 2023-09-30 at 10 31 39 PM" src="https://github.com/rubemfsv/clean-react-app/assets/94985341/09c619ca-24c0-4686-85a4-95413bb46c26">

**Comment by rubemfsv** [comment]
@Vijaykv5 I was thinking here... This way we should update the README always someone new contribute with the project.
What do you think about use the same way pact uses? You can check there:
https://github.dev/pact-foundation/pact-js/blob/master/README.md

In this way, it's only one image that update always someone new contribute. Don't forget to look at the existing section called "[Branches and contributions](https://github.com/rubemfsv/clean-react-app#bookmark_tabs-branches-and-contributions)". One thing you could do is to put the issues section before the branchs and contributions, and the collaborators after the branchs and contributions. Do you think it's better to call collaborators or contributors? Github call contributors I guess

**Comment by Vijaykv5** [comment]
Yeah its **"Contributors"**

I found that pact-js is using _contrib.rocks_ to get sync images of the contributors.

So do we need to follow the same thing. It would look like [this](https://contrib.rocks/image?repo=rubemfsv/clean-react-app).
we'll be just able to display the user-images only..

**Comment by rubemfsv** [comment]
Yes, I noticed that... I prefer displaying the pic and the username, but how to do this in an automated way like with contrib.rocks?

**Comment by Vijaykv5** [comment]
> Yes, I noticed that... I prefer displaying the pic and the username, but how to do this in an automated way like with contrib.rocks?

Not sure about the username, profile pic can be displayed as I mentioned earlier via contrib.rocks in automated way

**Comment by rubemfsv** [comment]
> > Yes, I noticed that... I prefer displaying the pic and the username, but how to do this in an automated way like with contrib.rocks?
> 
> Not sure about the username, profile pic can be displayed as I mentioned earlier via contrib.rocks in automated way

I think we can stick with contrib.rocks showing just the photos since we do this once and contrib.rocks updates when someone new contributes to the project. All contributors look better and display more information, but we will need to make anyone who opens a new PR change the documents with their information. :thinking: 
Don't forget to ensure commit messages are following the conventional commits 😄

**Comment by rubemfsv** [comment]
Resolved https://github.com/rubemfsv/clean-react-app/pull/32
