### ISSUE TITLE
Add templates for issues

### ISSUE THREAD

**Issue by Vijaykv5** [rubemfsv/clean-react-app#13]
It would be great if we can add templates for the issues. so contributors can catagorize the issues and raise issues

**Comment by Vijaykv5** [comment]
I would love to work on it

**Comment by rubemfsv** [comment]
Hey, @Vijaykv5! Thank you for your contribution with new ideas. It would be great if you could work on it :smile:
I used a personal pattern in the other issues, you can check it to see if it helps somehow

**Comment by Vijaykv5** [comment]
Please check on it @rubemfsv
