### ISSUE TITLE
Complete Web Page flow setup

### ISSUE THREAD

**Issue by Ashok-Kumar-dharanikota** [rubemfsv/clean-react-app#17]
**Description**

Please describe the Feature in detail.
We often find these sections common on most of the websites. 
CompanyLogo, Header, Side Navigation, and main content. 
When developer create new project. he need to implement this flow from scratch. This consuming more time for developer.

**Expected Behavior**
After Completing of Login and registration process. user sees the blank page. Here he need to create the side and top navigation and content again. why don't we include this flow too? we find this common design pattern in most of the websites, right?

What should happen?

**Screenshots (if applicable)**

Add screenshots or other media to help explain the issue.
![Screenshot 2023-10-01 000754](https://github.com/rubemfsv/clean-react-app/assets/103619560/62346ba0-9244-4478-af39-fe2afc79fe69)

**Additional Information**

Add any other context or information about the issue here.

I would like to work on this issue as a part of this HacktoberFest

**Comment by rubemfsv** [comment]
Hey @Ashok-Kumar-dharanikota! Good idea. Alright, remember a few things:
1. Follow the current architectural pattern
2. Follow clean code
3. Componentize it as a template to encompass the other internal pages

**Comment by Ashok-Kumar-dharanikota** [comment]
Sure @rubemfsv 🤝, thank you for considering my proposal ☺️. I will work on it and let you know the progress. Step by step.

**Comment by rubemfsv** [comment]
@Ashok-Kumar-dharanikota any doubts, you can contact me! Don't forget to ensure commit messages are following the conventional commits :smile:

**Comment by Ashok-Kumar-dharanikota** [comment]
Hi @rubemfsv 
I have one query to ask, as I want to run it in my localhost and I replaced the URL in webpack.prod.js and webpack.dev.js files with this 

```
      'process.env.API_URL': JSON.stringify('http://localhost:3000'),

```

I am getting a problem that is 

```
> @rubemfsv/clean-react-app@1.1.3 dev
> yarn dev:base -- --open

'yarn' is not recognized as an internal or external command,
operable program or batch file.
```

can you help me where it went wrong ?

**Comment by rubemfsv** [comment]
@Ashok-Kumar-dharanikota do you have yarn in your computer globally? Try to run "npm run dev" instead

**Comment by Ashok-Kumar-dharanikota** [comment]
No, i don't have yarn in my laptop. Mostly I use npm. I tried that command too and got this response. Should I install yarn ?

**Comment by rubemfsv** [comment]
@Ashok-Kumar-dharanikota you can use npm. Instead of run yarn, run "npm run"
"npm start", "npm run dev", "npm run test", and you dont neet to use or install yarn.

**Comment by Ashok-Kumar-dharanikota** [comment]
I tried 'npm start' didn't got the url open in tab and I manually copied and pasted in crome. 

this is the response 
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type function ([Function (anonymous)])
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at extname (node:path:837:5)
    at new View (C:\Users\ashok\source\repos\clean-react-app\node_modules\express\lib\view.js:56:14)
    at Function.render (C:\Users\ashok\source\repos\clean-react-app\node_modules\express\lib\application.js:587:12)
    at ServerResponse.render (C:\Users\ashok\source\repos\clean-react-app\node_modules\express\lib\response.js:1039:7)
    at C:\Users\ashok\source\repos\clean-react-app\index.js:7:7
    at Layer.handle [as handle_request] (C:\Users\ashok\source\repos\clean-react-app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ashok\source\repos\clean-react-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\Users\ashok\source\repos\clean-react-app\node_modules\express\lib\router\route.js:114:3)
```

**Comment by rubemfsv** [comment]
@Ashok-Kumar-dharanikota and the other commands? Which node version are you using? If you changed to
```
  plugins: [
    new DefinePlugin({
      'process.env.API_URL': JSON.stringify('http://localhost:3000/'),
    }),
    new HtmlWebpackPlugin({
      template: './template.dev.html',
    }),
  ],
```
its to work. Run` npm run dev` to run in dev mode after these changes.

**Comment by Ashok-Kumar-dharanikota** [comment]
Tried all commands, test command done few tests and then it's ended. And I followed the same pattern. 

I will update my node version once. If it's fixed i will let you know.

**Comment by rubemfsv** [comment]
@Ashok-Kumar-dharanikota it needed yarn, actually, but was fixed throught this https://github.com/rubemfsv/clean-react-app/issues/43
Please refresh your project and try again!

**Comment by Ashok-Kumar-dharanikota** [comment]
Thank you @rubemfsv 🤩,

Now it's working fine, but while logging in or registering. I am getting this response

```
Cannot read properties of undefined (reading 'status')
```
🤔 I tried to use the login credentials in the user.json file. But got the same response. 
I think it still has some configurations to do. I think we should also need to update the readme once.

**Comment by rubemfsv** [comment]
@Ashok-Kumar-dharanikota this problem sometimes appears when your endpoint doesn't return what was expected to the AccountModel. As it is a template, you should make the changes to fits your need. 
Workaround: Remove the Private property in src/main/routes/router.tsx for the dashboard. Do this only for development, don't commit this.

But you have a really good point, it would be nice to update readme and put instructions as where to change the environments, what do you think? If you want and if it would be good for your to the hacktoberfest, I also can open a issue to do this update and notify you to do this change (but only if you want it) :smile:

**Comment by Ashok-Kumar-dharanikota** [comment]
Sure 😄 after completing this issue I will work on the readme update. So it won't be an obstacle for new contributors. So they will directly start working on it and also helpful to those who use clean-react-app for their react project. 

And also want to ask one thing. 

How can we create a script that would ask questions like example...
"Do you want to use this template [y/n]"
"How many pages do you want for your project:" 

If the user enters 5. It will create 5 pages in both nav and side bar and it will Ask names for each file from the user. 

So the user doesn't need to manually rename his page names again.

I would like to know how i can make this. 🤔 which language or tool or script I have to use to make it work. I don't have much idea about scripts but like to learn if it's helpful. 😃

**Comment by rubemfsv** [comment]
Thank you for your proactivity with the README as well! It's very important!

Regarding your suggestion, I found it quite interesting! I will think a bit more about your idea to formalize something; it would be an incredible feature with tremendous potential, opening up new possibilities!  :rocket: 

For this, it's just pure JavaScript. There's a script in the project, located in the src/main/scripts/bin.js folder, and that's where the magic happens! We can consider this task for the future, and if you'd like, we can work together to make this learning experience happen here. :smile: 

There is a small issue in the bin.js of this project to adapts with user needs: https://github.com/rubemfsv/clean-react-app/issues/55

**Comment by Ashok-Kumar-dharanikota** [comment]
Hi @rubemfsv ,

After adding and modifying some files. The updated folder structure is

```
  main/
    factories/
      pages/
        Home/
        Explore/
        Aboutus/
        Contactus/
    routes/
      router.tsx
  presentation/
    components/
      TopNavigation/
    pages/
      Home/
      Explore/
      Aboutus/
      Contactus/

```

Did I followed the correct folder structure?

And this would be the Dashboard page

![image](https://github.com/rubemfsv/clean-react-app/assets/103619560/779fedec-d7cf-497e-86b5-1aa9b12d447d)

Along with Routing ...

![image](https://github.com/rubemfsv/clean-react-app/assets/103619560/60619a34-be58-4ef7-8e94-e819177c06c2)

I want to make the top navigation fixed position. so it won't disappear when moved to another page(little confused here 😅). I added some common page names which we find common in most of the websites. Please let me know if I have missed anything.

**Comment by rubemfsv** [comment]
Hey!

This article explains the architecture: https://dev.to/rubemfsv/clean-architecture-applying-with-react-40h6

I think you followed very well, but I think, for this moment, it would be good to not create the other pages, only the template, as you suggested. It's better to work in small tasks :smile: 

I think something like this would be good for this issue (as your first suggestion):
```
  presentation/
    components/
      Template/
        Header/
        Navigation/
      index.tsx
      styles.scss
    pages/
      Home/
```
and use this Template in all the pages, that would need it! Take a look in how I did in this project: https://github.com/rubemfsv/clean-react-chat
You can download it, after that, tell me because this is a private project that I used in a job interview haha :smile: 

![image](https://github.com/rubemfsv/clean-react-app/assets/11760617/69e55d74-29c8-4af1-a73f-b60fec883806)

**Comment by Ashok-Kumar-dharanikota** [comment]
Okay sure @rubemfsv , if there is a requirement in future issues we will update it. For now it would be static.

I thought that 😄😅, as I was creating the nav bar. It is good to create some common routes. So it would save time for developers. 

Sure I will go through this project. Seems like it's personally helpful for me too. I downloaded it

**Comment by Ashok-Kumar-dharanikota** [comment]
Hi @rubemfsv , 

as you said, I followed this structure.

```
  presentation/
    components/
      Template/
        Header/
        Navigation/
      index.tsx
      styles.scss
    pages/
      Home/
```

And I committed (Conventional) changes to my repo. please check once

https://github.com/Ashok-Kumar-dharanikota/clean-react-app

if everything was fine. I will create a PR. 😊

**Comment by rubemfsv** [comment]
@Ashok-Kumar-dharanikota hey! It should be 2 folders inside template folder. Template folder with its index.tsx and styles.scss and each one of the other with its own index.tsx and scss. Take a look at clean react chat and check how I did there! You will have the template that consumes the header and consumes the navigation, and display in the center the content.

It would look like:

```
  presentation/
    components/
      Template/
        Header/
              index.tsx // contains header
              styles.scss
        Navigation/
              index.tsx // contains navigation
              styles.scss
        index.tsx // mount header and navigation and provides a template
        styles.scss
    pages/
      Home/
```

**Comment by Ashok-Kumar-dharanikota** [comment]
Hi @rubemfsv 

as you said, I followed this structure. 

```
  presentation/
    components/
      Template/
        Header/
              index.tsx // contains header
              styles.scss
        Navigation/
              index.tsx // contains navigation
              styles.scss
        index.tsx // mount header and navigation and provides a template
        styles.scss
    pages/
      Home/
```

And I committed changes to my repo again. please check once. 😅

Did we need this page?
```
      Home/

```

 Header 

```
import React from 'react'
import Styles from './styles.scss'
import Navigation from '../Navigation'

const Header: React.FC = () => {
  return (
    <div className={Styles.Container}>
      <img
        className={Styles.logo}
        src="https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg"
      />

      <Navigation />
    </div>
  )
}

export default Header
```
Navigation 

```
import React from 'react'
import Styles from './styles.scss'

const Navigation: React.FC = () => {
  return (
    <nav>
      <ul className={Styles.navList}>
        <li className={Styles.navLink}>Home</li>
        <li className={Styles.navLink}>Explore</li>
        <li className={Styles.navLink}>About Us</li>
        <li className={Styles.navLink}>Contact Us</li>
      </ul>
    </nav>
  )
}

export default Navigation

```
Dashboard

```
import React from 'react'

import Styles from './styles.scss'
import Header from '@/presentation/components/Template/Header'

type DashboardProps = {}

const Dashboard: React.FC<DashboardProps> = () => {
  return (
    <div className={Styles.container}>
      <Header />

      <div className={Styles.App}>
        <img src="https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg" />
        <span>Start your development from here</span>
      </div>
    </div>
  )
}

export default Dashboard

```

https://github.com/Ashok-Kumar-dharanikota/clean-react-app

**Comment by rubemfsv** [comment]
@Ashok-Kumar-dharanikota did you see the clean react chat?

Sorry, don't need the home, only the existing dashboard!
```
  presentation/
    components/
      Template/
        Header/
              index.tsx // contains header
              styles.scss
        Navigation/
              index.tsx // contains navigation
              styles.scss
        index.tsx // mount header and navigation and provides a template
        styles.scss
    pages/
      Dashboard/
```
And dashboard should have be something like:

```
return (
    <Template>
      <div className={Styles.App}>
        <img src="https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg" />
        <span>Start your development from here</span>
      </div>
    </Template>
  );
};

```
The header and nav should be on Template, and Template should hold the content like this. Check again the clean-react-chat, please

**Comment by Ashok-Kumar-dharanikota** [comment]
Sorry, Now i got the point. i am able to wrap the dashboard inside the Template

I wrap the Header inside the Template. Because if the user wants to modify they can do it separately. and the Navigation was wrapped inside the Header. 
```
const Template: React.FC<TemplateProps> = ({ children }) => {
  return (
    <div className={Styles.container}>
      <Header />
      <div>
        {children}
      </div>
    </div>
  )
}
```
and Dashboard be like (as you shown)

```
return (
    <Template>
      <div className={Styles.App}>
        <img src="https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg" />
        <span>Start your development from here</span>
      </div>
    </Template>
  );
};

```

**Comment by rubemfsv** [comment]
Hey, @Ashok-Kumar-dharanikota!!! About the Dashboard file, perfect!

About the Template, you don't need the div holding children! Can you open a PR and then I will checking the points in your PR and we see together? 

I think for this task, we could have only a header, and then open other task later to put a navigation. What do you think? Because I think navigation can take more time, I don't know.

**Comment by Ashok-Kumar-dharanikota** [comment]
Okay sure. That's good idea to go step by step. Instead of wrapping things at once. 

That means should I remove the navigation and only keep the Header? 

I really appreciate your patience ☺️. As I keep asking questions 😅 and doing some mistakes thank you for guiding me through this. I learnt a lot about clean project structure and how important it is to split Big tasks into smaller pieces and work slowly and correctly.

**Comment by rubemfsv** [comment]
> Sure 😄 after completing this issue I will work on the readme update. So it won't be an obstacle for new contributors. So they will directly start working on it and also helpful to those who use clean-react-app for their react project.
> 
> And also want to ask one thing.
> 
> How can we create a script that would ask questions like example... "Do you want to use this template [y/n]" "How many pages do you want for your project:"
> 
> If the user enters 5. It will create 5 pages in both nav and side bar and it will Ask names for each file from the user.
> 
> So the user doesn't need to manually rename his page names again.
> 
> I would like to know how i can make this. 🤔 which language or tool or script I have to use to make it work. I don't have much idea about scripts but like to learn if it's helpful. 😃

@Ashok-Kumar-dharanikota would you still like to work in this Readme update?

**Comment by Ashok-Kumar-dharanikota** [comment]
Yes, of course 😄. I would like to update the readme file.

**Comment by rubemfsv** [comment]
@Ashok-Kumar-dharanikota can you create the issue? And we can improve the issue together :)
