### ISSUE TITLE
[DOCS] Create a GitHub PR Template

### ISSUE THREAD

**Issue by rubemfsv** [rubemfsv/clean-react-app#19]
**Description**

Please create a GitHub PR (Pull Request) template to streamline the process of submitting and reviewing pull requests in our repository.

**Expected Behavior**

The PR template should serve as a standardized guide for contributors to provide essential information when submitting pull requests. It should include sections for a clear title, a detailed description of the changes, and any relevant context.

**Actual Behavior**

Currently, we don't have a PR template in place, which can lead to inconsistent or incomplete information being provided with PR submissions. Having a template will improve the PR submission process and make it easier for reviewers to understand and assess the changes.

**Additional Information**

Adding a PR template will contribute to better organization and communication within our project. It will help both contributors and reviewers by ensuring that necessary information is included with each PR, streamlining the review process, and reducing back-and-forth discussions. Please create the template based on common PR guidelines and best practices.

Follow the [pact-js](https://github.com/pact-foundation/pact-js/) PR template pattern, but adapting to Clean React App context. Don't forget to ensure commit messages are following the conventional commits.

**Comment by oliviocandido** [comment]
Can I do this?
