### ISSUE TITLE
[DOCS] Add MIT License and Update README.md

### ISSUE THREAD

**Issue by rubemfsv** [rubemfsv/clean-react-app#20]
**Description**

Please add the MIT License to our project repository and update the README.md file accordingly.

**Expected Behavior**

The MIT License should be added to the project repository, and the README.md file should be modified to include information about the license, including a license badge and any relevant details about the license terms.

**Actual Behavior**

Currently, our project does not have a license specified, which can create confusion about how the code can be used and shared. It's essential to add a clear and permissive license to ensure that others can use the code with legal certainty.

**Screenshots (if applicable)**

N/A

**Additional Information**

By adding the MIT License and updating the README.md, we will make it clear to potential users and contributors how they can use, modify, and distribute the code. This action aligns with open-source best practices and ensures legal compliance. Please follow standard procedures for adding the MIT License to the repository. [Example](https://github.com/eslint/eslint/blob/main/LICENSE).

**Comment by oliviocandido** [comment]
Can I do this? :)

**Comment by akashroy1** [comment]
Hello @rubemfsv Can I work on this? I can see there has been no pull request since yesterday.

**Comment by rubemfsv** [comment]
> Hello @rubemfsv Can I work on this? I can see there has been no pull request since yesterday.

Hey @akashroy1, please select an issue with no one assigned or suggest a new one. I also have this other project: https://github.com/rubemfsv/Github-Explorer-Mobile-Clean-Architecture

You could open an issue to add e MIT there, as would do for this one, and I can accept. The other one is also on hacktoberfest

**Comment by rubemfsv** [comment]
https://github.com/rubemfsv/clean-react-app/pull/46
