### ISSUE TITLE
[DOCS] Create CONTRIBUTING.md and Update README.md

### ISSUE THREAD

**Issue by rubemfsv** [rubemfsv/clean-react-app#21]
**Description**

Please create a CONTRIBUTING.md file with detailed instructions for contributors and then update the README.md file to include a link to the CONTRIBUTING.md file.

**Expected Behavior**

The CONTRIBUTING.md file should be created, providing clear instructions on how contributors can contribute to our project. The README.md file should be updated to include a section with a link to the CONTRIBUTING.md file, making it easy for potential contributors to find the guidelines.

**Actual Behavior**

Currently, we lack a CONTRIBUTING.md file, which can make it challenging for new contributors to understand how they can get involved in our project effectively. By creating this file and linking it in the README, we can improve the onboarding experience for contributors.

**Screenshots (if applicable)**

N/A

**Additional Information**

Creating a CONTRIBUTING.md file is a standard practice in open-source projects. It helps maintainers and contributors collaborate more effectively by providing guidelines on code contributions, issue reporting, and other essential processes. Please refer to best practices and examples like the one found at [pact-foundation/pact-js CONTRIBUTING.md](https://github.com/pact-foundation/pact-js/blob/master/CONTRIBUTING.md) to create our own CONTRIBUTING.md file.

**Comment by oliviocandido** [comment]
Can I do this?
