### ISSUE TITLE
[DOCS] Create CHANGELOG.md

### ISSUE THREAD

**Issue by rubemfsv** [rubemfsv/clean-react-app#22]
**Description**

Please create a changelog.md file to document the changes, enhancements, and bug fixes made to our project over time.

**Expected Behavior**

The changelog.md file should be created in our project repository. It should follow a standardized format for documenting changes, including version numbers, release dates, and descriptions of changes made in each release.

**Actual Behavior**

Currently, we do not have a changelog file, making it challenging for users and contributors to track the progress and history of our project. By creating a changelog.md file, we can improve transparency and keep stakeholders informed about the evolution of our software.

**Screenshots (if applicable)**

N/A

**Additional Information**

Add any other context or information about the issue here.Having a changelog.md file is a common practice in software development. It serves as a valuable resource for users and contributors, helping them understand what has been added, modified, or fixed in each release. Please consider adopting a standard changelog format, and document changes in a clear and concise manner.
Example: https://github.com/pact-foundation/pact-js/blob/master/CHANGELOG.md

**Comment by oliviocandido** [comment]
Can I do this?
