### ISSUE TITLE
[DOCS] Create CODE_OF_CONDUCT.md and Add It to README.md

### ISSUE THREAD

**Issue by rubemfsv** [rubemfsv/clean-react-app#23]
**Description**

Please create a CODE_OF_CONDUCT.md file that outlines our project's code of conduct and then add a reference to it in the README.md file.

**Expected Behavior**

A CODE_OF_CONDUCT.md file should be added to our project repository, containing clear and concise guidelines for acceptable behavior within our community. Additionally, the README.md file should be updated to include a link or section that points to the code of conduct for easy reference.

**Actual Behavior**

Currently, our project does not have a code of conduct explicitly defined or documented. It is essential to establish and communicate clear expectations for behavior to foster a respectful and inclusive community around our project.

**Screenshots (if applicable)**
N/A

**Additional Information**

Having a code of conduct is a crucial step in creating a welcoming and inclusive environment for all contributors and users. It sets expectations for respectful and professional interactions within the project community. Please consider using established code of conduct templates or guidelines when creating the CODE_OF_CONDUCT.md file.
Don't copy, but get inspired by: https://github.com/pact-foundation/pact-js/blob/master/CODE_OF_CONDUCT.md

**Comment by victorevh** [comment]
I can do this? @rubemfsv

**Comment by rubemfsv** [comment]
@victorevh done! Don't forget to ensure commit messages are following the conventional commits 😄

**Comment by akashroy1** [comment]
Hello @rubemfsv I can see there is no pull request for this issue. I would like to work on this problem.

**Comment by rubemfsv** [comment]
@akashroy1, unfortunately, @victorevh asked first and it has been less than 12 hours since I assigned him. Please, check the other unassigned open issues or suggest a new one 😄

**Comment by rubemfsv** [comment]
Done at https://github.com/rubemfsv/clean-react-app/pull/37
