### ISSUE TITLE
[FEATURE] Create File Type Validator

### ISSUE THREAD

**Issue by rubemfsv** [rubemfsv/clean-react-app#26]
**Description**

For file upload fields, checks that the uploaded file is of an allowed file type (e.g., image, PDF, document).

**Expected Behavior**

The File Type Validator should perform the following when validating uploaded files:

1. Identify the file's format or type by examining its header or content.
2. Compare the detected file type to a predefined list of allowed file types/extensions.
3. Reject files that do not match any of the allowed file types/extensions.
4. Optionally, provide detailed error messages indicating why a file was rejected (e.g., "Invalid file format").
5. Ensure that the validation process is case-insensitive to handle file extensions in a consistent manner.
6. Support both client-side and server-side validation, with a preference for server-side validation to prevent malicious uploads.

This behavior ensures that the File Type Validator effectively filters and permits only the specified file types, enhancing security and data integrity within the system. It helps prevent potentially harmful or unwanted file uploads while providing clear feedback to users about acceptable file formats.

**Additional Information**

Consider implementing this validator along with a corresponding unit test in the "validators" directory, alongside the existing validators.

**Comment by ChiragAgg5k** [comment]
Hey, I can work on this issue. Can you assign it to me?

**Comment by rubemfsv** [comment]
@ChiragAgg5k sure! Don't forget to ensure commit messages are following the conventional commits!

**Comment by ChiragAgg5k** [comment]
Hey @rubemfsv , i was a bit confused. Do i need to modify the existing Input component or create a new component? (It's probably not the latter but still confirming). Thanks

**Comment by rubemfsv** [comment]
@ChiragAgg5k I don't think you undertood the issue. It's neither modifying existing component or creating a new one. What you should do is creating a new validator for files, which verify the type. Its a validator as min and max length or required field, to build the validations of the fields

**Comment by ChiragAgg5k** [comment]
Ohh okay. Got it 👍

**Comment by rubemfsv** [comment]
@ChiragAgg5k are you still working on this?

**Comment by ChiragAgg5k** [comment]
Really sorry i am currently occupied with University exams. You can unassign me

**Comment by Arnav-2004** [comment]
Hello @rubemfsv, could you kindly assign this issue to me? I am interested in taking on this task.

**Comment by rubemfsv** [comment]
@Arnav-2004 sure!

**Comment by Arnav-2004** [comment]
Can you please guide me on how to test this feature with the current routes? I don't see any field for uploading files.

**Comment by rubemfsv** [comment]
Hey, @Arnav-2004, if you test with unit testing to cover all the particularities, it is alright! There are validators with unit testing that you can used by example

**Comment by Arnav-2004** [comment]
Thanks for you response @rubemfsv, I will create a PR soon.

**Comment by rubemfsv** [comment]
Thanks, @Arnav-2004! I've put some considerations on the PR
