### ISSUE TITLE
[FEATURE] Create Pattern Validator

### ISSUE THREAD

**Issue by rubemfsv** [rubemfsv/clean-react-app#28]
**Description**

 Checks if a field matches a specific pattern or regular expression, which can be useful for custom formatting requirements.

**Expected Behavior**

The Pattern Validator should perform the following when validating input against a specified pattern or regular expression:

1. Pattern Matching: Check whether the input string matches the specified pattern or regular expression.
3. Case Sensitivity: Provide an option to perform case-sensitive or case-insensitive pattern matching, depending on the use case.
5. Validation Result: Return a validation result indicating whether the input string matches the pattern or not.
7. Error Messages: Offer clear and customizable error messages when the input does not conform to the expected pattern, including details about the pattern requirements.
9. Support Custom Patterns: Allow for the validation of custom patterns, enabling flexibility in enforcing various format constraints.
11. Pattern Explanation: Optionally, provide a description or explanation of the expected pattern to guide users in providing valid input.

This behavior ensures that the Pattern Validator can effectively validate input against specified patterns or regular expressions, helping enforce specific format requirements and providing valuable feedback to users when input does not meet those requirements.

**Additional Information**

Consider implementing this validator along with a corresponding unit test in the "validators" directory, alongside the existing validators.

**Comment by rockingrohit9639** [comment]
@rubemfsv can I work on this ?

**Comment by rubemfsv** [comment]
@rockingrohit9639 of course! Don't forget to ensure commit messages are following the conventional commits 😄

**Comment by rockingrohit9639** [comment]
> @rockingrohit9639 of course! Don't forget to ensure commit messages are following the conventional commits 😄

Sure @rubemfsv, Thanks for assigning
