### ISSUE TITLE
[FEATURE] Create Max Length Validator

### ISSUE THREAD

**Issue by rubemfsv** [rubemfsv/clean-react-app#29]
**Description**

Please describe the Feature in detail.

The Max Length Validator should validate an input string by checking if it does not exceed a specified maximum character length:

2. Length Check: Verify that the length of the input string does not exceed the specified maximum character length.
4. Validation Result: Return a validation result indicating whether the input string's length is within the acceptable limit or not.
6. Error Message: Provide a clear and customizable error message when the input string exceeds the maximum length, indicating the maximum allowed length.
8. Use in Combination: Allow the Max Length Validator to be used in combination with other validators to provide comprehensive validation for complex input scenarios.

This behavior ensures that the Max Length Validator effectively enforces a maximum character limit for input strings, helping maintain data integrity and providing feedback to users when they exceed the specified length constraint. Look at the min length validator that is already in the system.

**Additional Information**

Consider implementing this validator along with a corresponding unit test in the "validators" directory, alongside the existing validators.

**Comment by boredcity** [comment]
happy to help out with this one, you can assign me.

**Comment by rubemfsv** [comment]
@boredcity done! Don't forget to ensure commit messages are following the conventional commits 😄
