### ISSUE TITLE
Erro ao utilizar módulo node-sass 

### ISSUE THREAD

**Issue by guilhermeabell** [rubemfsv/clean-react-app#3]
O pacote node-sass não está sendo mais mantido, ocorrendo vários erros no console dependendo da versão utilizada,  e em ambientes OSX com arquitetura ARM64 sendo até imcompativel, impedindo o uso do boilerplate.

**Comment by guilhermeabell** [comment]
#4

**Comment by rubemfsv** [comment]
Issue finalizada pois a versão do node-sass foi atualizada junto com outras libs, e os erros aparentemente pararam de exibir. Se voltar a aparecer, recomendo abrir uma issue com prints
