### ISSUE TITLE
[FEATURE] Create .npmignore File for Improved Package Optimization

### ISSUE THREAD

**Issue by rubemfsv** [rubemfsv/clean-react-app#30]
**Description**

This issue proposes the creation of a .npmignore file within our project repository. The primary goal is to enhance the efficiency, security, and cleanliness of our npm package distribution process. The .npmignore file serves as a critical tool for specifying which files and directories should be excluded when publishing our package to the npm registry.

**Expected** Behavior

The expected behavior is to add a .npmignore file to our project repository. This file will allow us to specify which files and directories should be excluded when publishing our package to the npm registry. By defining these exclusion rules, we can optimize the size of the distributed package and ensure that only essential files are included.

**Screenshots (if applicable)**

N/A

**Additional Information**

The addition of a .npmignore file is a best practice in Node.js and npm projects. It will help us enhance the security, efficiency, and cleanliness of our npm package by excluding development files, sensitive information, and other non-essential assets. This improvement aligns with industry standards for npm package management.

**Comment by victorevh** [comment]
I would like solve this issue

**Comment by rubemfsv** [comment]
@victorevh done! Don't forget to ensure commit messages are following the conventional commits 😄

**Comment by rubemfsv** [comment]
fix  https://github.com/rubemfsv/clean-react-app/pull/42
