### ISSUE TITLE
[ENHANCEMENT] Enhance Error Handling with Enumerated Error Messages

### ISSUE THREAD

**Issue by rubemfsv** [rubemfsv/clean-react-app#35]
**Description**

This enhancement aims to add error messages to an enumerator. These error messages will be organized into separate folders, each containing its own "enums" folder to maintain a structured hierarchy, even for error enumerations.

**Expected Behavior**

Upon implementation of this enhancement, the error handling system will be more robust and structured. Error messages will be accessible through enumerations, making it easier to manage and maintain error-related logic in the codebase.

**Screenshots (if applicable)**

Add screenshots or other media to help explain the issue.

**Additional Information**

This enhancement will improve code organization and maintainability by centralizing error messages within enumerations, following a folder structure that aligns with the project's architecture.

**Comment by victorevh** [comment]
I can do this?

**Comment by rubemfsv** [comment]
@victorevh sure! Done. Don't forget the commits best practices.
