### ISSUE TITLE
[FEATURE] Add Prettier and Implement It in the Project

### ISSUE THREAD

**Issue by rubemfsv** [rubemfsv/clean-react-app#39]
**Issue Title:**

**Description:**
We are considering the implementation of Prettier in our project. Prettier is an opinionated code formatter that helps maintain a consistent coding style across the project. This feature request aims to add Prettier to our development workflow and ensure that our codebase adheres to a unified coding style.

**Expected Behavior:**
Upon implementing Prettier, we expect the following behavior:
1. Automatic code formatting: Prettier should automatically format code files according to predefined style rules.
2. Consistency: Code formatting should be consistent across the entire project, reducing stylistic variations.
3. Improved code readability: Formatted code is more readable and easier to maintain.

**Screenshots (if applicable):**
N/A

**Additional Information:**
Adding Prettier to our project can help us enhance code quality, collaboration, and maintainability. It is a step towards a more organized and efficient development process.

**Comment by rockingrohit9639** [comment]
@rubemfsv Can I work on this ?

**Comment by rubemfsv** [comment]
@rockingrohit9639 sure! Done. Don't forget the commits best practices.

**Comment by rockingrohit9639** [comment]
> @rockingrohit9639 sure! Done. Don't forget the commits best practices.

Sure.

**Comment by rockingrohit9639** [comment]
Hi @rubemfsv just wanted to confirm one thing. Are these rules fine or is there any addition or deletion required ?
```json
{
  "trailingComma": "es5",
  "tabWidth": 2,
  "semi": false,
  "singleQuote": true,
  "endOfLine": "lf"
}

```

**Comment by rubemfsv** [comment]
Hey, @rockingrohit9639, this is great!

**Comment by rubemfsv** [comment]
Hey, @rockingrohit9639, I put some considerations
