### ISSUE TITLE
[FEATURE] Add Commitlint and Hook with Husky

### ISSUE THREAD

**Issue by rubemfsv** [rubemfsv/clean-react-app#41]
**Description:**
We are considering the implementation of Commitlint in our project along with integration with Husky. Commitlint is a tool that checks commit messages against defined rules and patterns to ensure they follow a consistent and meaningful format. By adding Commitlint and configuring it to work with Husky, we can enforce best practices for commit messages in our project.

**Expected Behavior:**
Upon implementing Commitlint and hooking it with Husky, we expect the following behavior:
1. Commit Message Conventions: Commit messages should follow predefined conventions, ensuring consistency and readability.
2. Pre-Commit Checks: Commitlint should run automatically before each commit, checking the commit message against the defined rules.
3. Enforced Best Practices: Developers will be prompted to follow best practices when writing commit messages, such as using a conventional commit style.

**Screenshots (if applicable):**
N/A

**Additional Information:**
Adding Commitlint and integrating it with Husky is a valuable step in maintaining a clean and well-organized commit history. It helps enforce commit message conventions, making it easier to understand the purpose and context of each commit. This feature will contribute to better collaboration and code quality in our project.

**Comment by victorevh** [comment]
@rubemfsv i can do it?

**Comment by rubemfsv** [comment]
@victorevh sure!

**Comment by rubemfsv** [comment]
https://github.com/rubemfsv/clean-react-app/pull/53
