### ISSUE TITLE
Implement Unit Tests for Button Component

### ISSUE THREAD

**Issue by rubemfsv** [rubemfsv/clean-react-app#9]
This issue is focused on implementing unit tests for the Button component within our project. Unit testing is a crucial aspect of software development that helps ensure the reliability and correctness of individual code units, such as components.

**Goals:**

- Create comprehensive unit tests for the Button component to validate its functionality.
- Verify that the Button component behaves as expected in various scenarios.
- Ensure that any changes or updates to the Button component in the future do not introduce regressions.

**Tasks:**

1. Write unit tests that cover different aspects of the Button component (e.g., rendering, interaction, event handling).
2. Include test cases for different Button states (e.g., normal, disabled, active).
3. Validate the accessibility of the Button component, ensuring it meets accessibility standards.
4. Ensure that the tests provide sufficient code coverage for the Button component.

**Guidelines:**

- Follow best practices for unit testing.
- Write clear and descriptive test cases that cover both typical and edge cases.
- Pay attention to code quality, readability, and maintainability when writing tests.

**Comment by Danishkar** [comment]
I would like to work on this issue.

**Comment by rubemfsv** [comment]
@Danishkar sure! Don't forget to ensure commit messages are following the conventional commits :smile:

**Comment by coldrohak** [comment]
Hey @rubemfsv, I would like to work on this

**Comment by rubemfsv** [comment]
@coldrohak done!

**Comment by Dhruvrode** [comment]
Hey @rubemfsv,  Can i work on it?

**Comment by rubemfsv** [comment]
@Dhruvrode there is an open PR for this issue! Please, check our other open issues

**Comment by Dhruvrode** [comment]
Okay np!
